# Generated by Django 4.0.5 on 2022-06-30 02:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateField(default=datetime.datetime(2022, 6, 30, 8, 3, 31, 288760))),
                ('status', models.CharField(choices=[('applied', 'applied'), ('reviewing', 'reviewing'), ('selected', 'selected'), ('rejected', 'rejected'), ('waiting', 'waiting')], max_length=255)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
